// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APICondSecurity.Models;

[Table("uf")]
public partial class Uf
{
    [Key]
    [Column("id_uf")]
    public int IdUf { get; set; }

    [Required]
    [Column("nome")]
    [StringLength(30)]
    public string Nome { get; set; }

    [Required]
    [Column("sigla")]
    [StringLength(2)]
    public string Sigla { get; set; }

    [Column("id_cidade")]
    public int IdCidade { get; set; }

    [InverseProperty("IdUfNavigation")]
    public virtual ICollection<Endereco> Endereco { get; set; } = new List<Endereco>();

    [ForeignKey("IdCidade")]
    [InverseProperty("Uf")]
    public virtual Cidade IdCidadeNavigation { get; set; }
}