// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APICondSecurity.Models;

[PrimaryKey("IdVeiculo", "Placa")]
[Table("veiculo")]
public partial class Veiculo
{
    [Key]
    [Column("id_veiculo")]
    public int IdVeiculo { get; set; }

    [Key]
    [Column("placa")]
    [StringLength(7)]
    public string Placa { get; set; }

    [Required]
    [Column("marca")]
    [StringLength(20)]
    public string Marca { get; set; }

    [Required]
    [Column("modelo")]
    [StringLength(20)]
    public string Modelo { get; set; }

    [Required]
    [Column("cor")]
    [StringLength(20)]
    public string Cor { get; set; }

    [Column("ano")]
    public int Ano { get; set; }

    [Column("id_condominio")]
    public int IdCondominio { get; set; }

    [ForeignKey("IdCondominio")]
    [InverseProperty("Veiculo")]
    public virtual Condominio IdCondominioNavigation { get; set; }
}