// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APICondSecurity.Models;

[Table("veiculo_terceiro")]
public partial class VeiculoTerceiro
{
    [Key]
    [Column("id_veiculo_terceiro")]
    public int IdVeiculoTerceiro { get; set; }

    [Required]
    [Column("placa")]
    [StringLength(255)]
    public string Placa { get; set; }

    [Column("id_notificacao")]
    public int? IdNotificacao { get; set; }

    [Column("id_permissao")]
    public int? IdPermissao { get; set; }

    [Column("id_veiculo")]
    public int? IdVeiculo { get; set; }

    [Column("id_usuario")]
    public int? IdUsuario { get; set; }

    [ForeignKey("IdNotificacao")]
    [InverseProperty("VeiculoTerceiro")]
    public virtual Notificacao IdNotificacaoNavigation { get; set; }

    [ForeignKey("IdPermissao")]
    [InverseProperty("VeiculoTerceiro")]
    public virtual Permissao IdPermissaoNavigation { get; set; }

    [ForeignKey("IdUsuario")]
    [InverseProperty("VeiculoTerceiro")]
    public virtual Usuario IdUsuarioNavigation { get; set; }

    [InverseProperty("IdVeiculoTerceiroNavigation")]
    public virtual ICollection<Registros> Registros { get; set; } = new List<Registros>();
}