// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APICondSecurity.Models;

[Table("veiculo_usuario")]
public partial class VeiculoUsuario
{
    [Key]
    [Column("id_veiculo_usuario")]
    public int IdVeiculoUsuario { get; set; }

    [Required]
    [Column("placa")]
    [StringLength(7)]
    public string Placa { get; set; }

    [Column("id_usuario")]
    public int IdUsuario { get; set; }

    [Column("id_veiculo")]
    public int? IdVeiculo { get; set; }

    [Column("id_RFID")]
    public int IdRfid { get; set; }

    [ForeignKey("IdRfid")]
    [InverseProperty("VeiculoUsuario")]
    public virtual Rfid IdRf { get; set; }

    [ForeignKey("IdUsuario")]
    [InverseProperty("VeiculoUsuario")]
    public virtual Usuario IdUsuarioNavigation { get; set; }

    [InverseProperty("IdVeiculoUsuarioNavigation")]
    public virtual ICollection<Registros> Registros { get; set; } = new List<Registros>();
}