// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APICondSecurity.Infra.Data.Models;

[PrimaryKey("IdCamera", "IpCamera")]
[Table("cameras")]
public partial class Cameras
{
    [Key]
    [Column("id_camera")]
    public int IdCamera { get; set; }

    [Column("posicao")]
    [StringLength(20)]
    public string Posicao { get; set; }

    [Column("tipo")]
    [StringLength(20)]
    public string Tipo { get; set; }

    [Key]
    [Column("ip_camera")]
    [StringLength(30)]
    public string IpCamera { get; set; }

    [Column("id_condominio")]
    public int IdCondominio { get; set; }

    [ForeignKey("IdCondominio")]
    [InverseProperty("Cameras")]
    public virtual Condominio IdCondominioNavigation { get; set; }
}