// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APICondSecurity.Infra.Data.Models;

[Table("notificacao")]
public partial class Notificacao
{
    [Key]
    [Column("id_notificacao")]
    public int IdNotificacao { get; set; }

    [Column("mensagem")]
    public string Mensagem { get; set; }

    [Column("data_hora")]
    [Precision(6, 0)]
    public TimeOnly DataHora { get; set; }

    [Column("tipo")]
    [MaxLength(1)]
    public char? Tipo { get; set; }

    [Column("imagem")]
    [StringLength(255)]
    public string Imagem { get; set; }

    [Column("situacao")]
    [MaxLength(1)]
    public char? Situacao { get; set; }

    [Column("id_usuario")]
    public int IdUsuario { get; set; }

    [ForeignKey("IdUsuario")]
    [InverseProperty("Notificacao")]
    public virtual Usuario IdUsuarioNavigation { get; set; }

    [InverseProperty("IdNotificacaoNavigation")]
    public virtual ICollection<Permissao> Permissao { get; set; } = new List<Permissao>();

    [InverseProperty("IdNotificacaoNavigation")]
    public virtual ICollection<VeiculoTerceiro> VeiculoTerceiro { get; set; } = new List<VeiculoTerceiro>();
}