// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APICondSecurity.Infra.Data.Models;

[Table("portao")]
public partial class Portao
{
    [Key]
    [Column("id_portao")]
    public int IdPortao { get; set; }

    [Required]
    [Column("nome")]
    [StringLength(20)]
    public string Nome { get; set; }

    [Column("id_condominio")]
    public int IdCondominio { get; set; }

    [ForeignKey("IdCondominio")]
    [InverseProperty("Portao")]
    public virtual Condominio IdCondominioNavigation { get; set; }

    [InverseProperty("IdPortaoNavigation")]
    public virtual ICollection<Registros> Registros { get; set; } = new List<Registros>();
}