// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APICondSecurity.Infra.Data.Models;

[Table("registros")]
public partial class Registros
{
    [Key]
    [Column("id_registros")]
    public int IdRegistros { get; set; }

    [Column("data_hora_entrada", TypeName = "timestamp(6) without time zone")]
    public DateTime? DataHoraEntrada { get; set; }

    [Column("data_hora_saida", TypeName = "timestamp(6) without time zone")]
    public DateTime? DataHoraSaida { get; set; }

    [Required]
    [Column("placa")]
    [StringLength(7)]
    public string Placa { get; set; }

    [Column("id_veiculo_usuario")]
    public int? IdVeiculoUsuario { get; set; }

    [Column("id_portao")]
    public int IdPortao { get; set; }

    [Column("id_veiculo_terceiro")]
    public int? IdVeiculoTerceiro { get; set; }

    [Column("id_usuario")]
    public int IdUsuario { get; set; }

    [Column("id_veiculo")]
    public int? IdVeiculo { get; set; }

    [Column("tag")]
    [StringLength(18)]
    public string Tag { get; set; }

    [ForeignKey("IdPortao")]
    [InverseProperty("Registros")]
    public virtual Portao IdPortaoNavigation { get; set; }

    [ForeignKey("IdVeiculoTerceiro")]
    [InverseProperty("Registros")]
    public virtual VeiculoTerceiro IdVeiculoTerceiroNavigation { get; set; }

    [ForeignKey("IdVeiculoUsuario")]
    [InverseProperty("Registros")]
    public virtual VeiculoUsuario IdVeiculoUsuarioNavigation { get; set; }
}