// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APICondSecurity.Infra.Data.Models;

[Table("residencia")]
public partial class Residencia
{
    [Key]
    [Column("id_residencia")]
    public int IdResidencia { get; set; }

    [Column("numero")]
    public int Numero { get; set; }

    [Column("bloco")]
    [StringLength(20)]
    public string Bloco { get; set; }

    [Column("quadra")]
    [StringLength(20)]
    public string Quadra { get; set; }

    [Column("rua")]
    [StringLength(50)]
    public string Rua { get; set; }

    [Column("id_condominio")]
    public int IdCondominio { get; set; }

    [ForeignKey("IdCondominio")]
    [InverseProperty("Residencia")]
    public virtual Condominio IdCondominioNavigation { get; set; }

    [InverseProperty("IdResidenciaNavigation")]
    public virtual ICollection<Usuario> Usuario { get; set; } = new List<Usuario>();
}