// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APICondSecurity.Infra.Data.Models;

[Table("RFID")]
public partial class Rfid
{
    [Key]
    [Column("id_RFID")]
    public int IdRfid { get; set; }

    [Column("numero")]
    public string Numero { get; set; }

    [Column("situacao")]
    public char Situacao { get; set; }

    [Column("id_condominio")]
    public int IdCondominio { get; set; }

    [ForeignKey("IdCondominio")]
    [InverseProperty("Rfid")]
    public virtual Condominio IdCondominioNavigation { get; set; }

    [InverseProperty("IdRf")]
    public virtual ICollection<VeiculoUsuario> VeiculoUsuario { get; set; } = new List<VeiculoUsuario>();
}