// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APICondSecurity.Infra.Data.Models;

[Table("usuario")]
public partial class Usuario
{
    [Key]
    [Column("id_usuario")]
    public int IdUsuario { get; set; }

    [Required]
    [Column("nome")]
    [StringLength(50)]
    public string Nome { get; set; }

    [Required]
    [Column("email")]
    [StringLength(50)]
    public string Email { get; set; }

    [Required]
    [Column("senha")]
    [StringLength(255)]
    public string Senha { get; set; }

    [Column("telefone")]
    [StringLength(255)]
    public string Telefone { get; set; }

    [Required]
    [Column("cpf")]
    [StringLength(255)]
    public string Cpf { get; set; }

    [Column("situacao")]
    [StringLength(2)]
    public string Situacao { get; set; }

    [Column("id_residencia")]
    public int IdResidencia { get; set; }

    [Column("id_condominio")]
    public int IdCondominio { get; set; }

    [Column("id_tipo_usuario")]
    public int IdTipoUsuario { get; set; }

    [ForeignKey("IdCondominio")]
    [InverseProperty("Usuario")]
    public virtual Condominio IdCondominioNavigation { get; set; }

    [ForeignKey("IdResidencia")]
    [InverseProperty("Usuario")]
    public virtual Residencia IdResidenciaNavigation { get; set; }

    [ForeignKey("IdTipoUsuario")]
    [InverseProperty("Usuario")]
    public virtual TipoUsuario IdTipoUsuarioNavigation { get; set; }

    [InverseProperty("IdUsuarioNavigation")]
    public virtual ICollection<Notificacao> Notificacao { get; set; } = new List<Notificacao>();

    [InverseProperty("IdUsuarioNavigation")]
    public virtual ICollection<VeiculoTerceiro> VeiculoTerceiro { get; set; } = new List<VeiculoTerceiro>();

    [InverseProperty("IdUsuarioNavigation")]
    public virtual ICollection<VeiculoUsuario> VeiculoUsuario { get; set; } = new List<VeiculoUsuario>();
}