// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APICondSecurity.Domain.Models;

[Table("endereco")]
public partial class Endereco
{
    [Key]
    [Column("id_endereco")]
    public int IdEndereco { get; set; }

    [Required]
    [Column("rua")]
    [StringLength(30)]
    public string Rua { get; set; }

    [Column("numero")]
    public int? Numero { get; set; }

    [Required]
    [Column("bairro")]
    [StringLength(30)]
    public string Bairro { get; set; }

    [Required]
    [Column("cep")]
    [StringLength(9)]
    public string Cep { get; set; }

    [Column("complemento")]
    [StringLength(100)]
    public string Complemento { get; set; }

    [Column("id_uf")]
    public int IdUf { get; set; }

    [InverseProperty("IdEnderecoNavigation")]
    public virtual ICollection<Condominio> Condominio { get; set; } = new List<Condominio>();

    [ForeignKey("IdUf")]
    [InverseProperty("Endereco")]
    public virtual Uf IdUfNavigation { get; set; }
}