// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APICondSecurity.Domain.Models;

[Table("permissao")]
public partial class Permissao
{
    [Key]
    [Column("id_permissao")]
    public int IdPermissao { get; set; }

    [Column("situacao")]
    [MaxLength(1)]
    public char Situacao { get; set; }

    [Column("id_notificacao")]
    public int IdNotificacao { get; set; }

    [ForeignKey("IdNotificacao")]
    [InverseProperty("Permissao")]
    public virtual Notificacao IdNotificacaoNavigation { get; set; }

    [InverseProperty("IdPermissaoNavigation")]
    public virtual ICollection<VeiculoTerceiro> VeiculoTerceiro { get; set; } = new List<VeiculoTerceiro>();
}